AWSTemplateFormatVersion: "2010-09-09"
Description: Firebase proof of concept

Parameters:
  RepoName:
    Type: String
    Description: The name of the GitHub repository

  LambdaCodeVersion:
    Type: String
    Description: Version ID of the Lambda code in the S3 bucket

  LambdaLayerVersion:
    Type: String
    Description: Version ID of the Lambda dependencies in the S3 bucket

  Stage:
    Type: String
    Description: Deployment stage. master->prod, dev->dev, test->test

Resources:
  AuthLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: src.lambda.auth.lambda_handler
      Role: !GetAtt AuthExecutionRole.Arn
      Code:
        S3Bucket: lambda-code-tests
        S3Key: !Sub "${RepoName}/lambda_code.zip"
        S3ObjectVersion: !Ref LambdaCodeVersion
      Runtime: python3.8
      FunctionName: firebase-auth
      Layers:
        - !Ref DependenciesLambdaLayer
      Environment:
        Variables:
          FIREBASE_CREDENTIALS: '{{resolve:secretsmanager:firebase:SecretString}}'


  GetUserLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: src.lambda.get_user.lambda_handler
      Role: !GetAtt GetUserExecutionRole.Arn
      Code:
        S3Bucket: lambda-code-tests
        S3Key: !Sub "${RepoName}/lambda_code.zip"
        S3ObjectVersion: !Ref LambdaCodeVersion
      Runtime: python3.8
      FunctionName: get-user
      Layers:
        - !Ref DependenciesLambdaLayer

  CreateUserLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: src.lambda.create_user.lambda_handler
      Role: !GetAtt CreateUserExecutionRole.Arn
      Code:
        S3Bucket: lambda-code-tests
        S3Key: !Sub "${RepoName}/lambda_code.zip"
        S3ObjectVersion: !Ref LambdaCodeVersion
      Runtime: python3.8
      FunctionName: create-user
      Layers:
        - !Ref DependenciesLambdaLayer

  AuthExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
        - PolicyName: SecretsManagerExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:firebase*"

  AuthLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref AuthLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub
        - 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*'
        - ApiId: !Ref ApiGatewayRestApi

  GetUserExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"

  CreateUserExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:table/users*"

  DependenciesLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: lambda-dependencies
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: lambda-dependencies-test
        S3Key: !Sub "${RepoName}/dependencies_layer.zip"
        S3ObjectVersion: !Ref LambdaLayerVersion

  ## DynamoDb

  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: uid
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: uid
          KeyType: HASH
        - AttributeName: email
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ## API Gateway

  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${RepoName}-API'

  UserResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt 'ApiGatewayRestApi.RootResourceId'
      PathPart: user

  GetUserMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref UserResource
      HttpMethod: GET
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref AuthLambdaAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
          - LambdaArn: !GetAtt GetUserLambda.Arn

  CreateUserMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref UserResource
      HttpMethod: POST
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref AuthLambdaAuthorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
          - LambdaArn: !GetAtt CreateUserLambda.Arn

  AuthLambdaAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: 'AuthLambdaAuthorizer'
      RestApiId: !Ref ApiGatewayRestApi
      Type: TOKEN
      IdentitySource: 'method.request.header.Authorization'
      AuthorizerUri: !Sub
        - 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations'
        - LambdaArn: !GetAtt AuthLambda.Arn

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref GetUserLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub
        - 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*'
        - ApiId: !Ref ApiGatewayRestApi

  CreateUserInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref CreateUserLambda
      Action: 'lambda:InvokeFunction'
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub
        - 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/*'
        - ApiId: !Ref ApiGatewayRestApi

  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - GetUserMethod
      - CreateUserMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      StageName: !Ref Stage
      Description: !Sub 'Deployment for ${Stage} stage'

#  ApiGatewayStage:
#    Type: 'AWS::ApiGateway::Stage'
#    UpdateReplacePolicy: Delete
#    DeletionPolicy: Retain
#    Properties:
#      StageName: !Ref Stage
#      Description: !Sub 'Stage for ${Stage}'
#      RestApiId: !Ref ApiGatewayRestApi
#      DeploymentId: !Ref ApiGatewayDeployment

  AccessDeniedGatewayResponse:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseType: ACCESS_DENIED
      RestApiId: !Ref 'ApiGatewayRestApi'
      StatusCode: '403'
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      ResponseTemplates:
        application/json: "{ \"message\": \"Access Denied!\" }"
